env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
plugins:
  - html
settings:
  html/html-extensions:
  - ".html"
  - ".vue"
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
